==87== Memcheck, a memory error detector
==87== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==87== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==87== Command: ./alpine-kubectl-delta -n ql-ovn pod
==87==
==87== Jump to the invalid address stated on the next line
==87==    at 0x0: ???
==87==    by 0xE32AC9: openssl::ssl::SslMethod::tls (mod.rs:319)
==87==    by 0xD9CD14: kube_client::client::tls::openssl_tls::ssl_connector_builder (tls.rs:269)
==87==    by 0xC3C769: <kube_client::config::Config as kube_client::client::config_ext::ConfigExt>::openssl_ssl_connector_builder (config_ext.rs:254)
==87==    by 0xC3C89E: <kube_client::config::Config as kube_client::client::config_ext::ConfigExt>::openssl_https_connector_with_connector (config_ext.rs:271)
==87==    by 0xC0AB1A: <kube_client::client::builder::ClientBuilder<tower::util::boxed::sync::BoxService<http::request::Request<hyper::body::body::Body>,http::response::Response<alloc::boxed::Box<dyn http_body::Body+Data = bytes::bytes::Bytes+Error = alloc::boxed::Box<dyn std::error::Error+core::marker::Send+core::marker::Sync>+core::marker::Send+core::marker::Unpin>>,alloc::boxed::Box<dyn std::error::Error+core::marker::Send+core::marker::Sync>>> as core::convert::TryFrom<kube_client::config::Config>>::try_from (builder.rs:88)
==87==    by 0xD2EFE7: <kube_client::client::Client as core::convert::TryFrom<kube_client::config::Config>>::try_from (mod.rs:456)
==87==    by 0x34EDE9: kube_client::client::Client::try_default::{{closure}} (mod.rs:128)
==87==    by 0x2CE156: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (mod.rs:91)
==87==    by 0x2BE965: kubectl_delta::main::{{closure}} (main.rs:100)
==87==    by 0x2CD5F8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (mod.rs:91)
==87==    by 0x31E2DF: tokio::park::thread::CachedParkThread::block_on::{{closure}} (thread.rs:267)
==87==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==87==
==87==
==87== Process terminating with default action of signal 11 (SIGSEGV)
==87==  Bad permissions for mapped region at address 0x0
==87==    at 0x0: ???
==87==    by 0xE32AC9: openssl::ssl::SslMethod::tls (mod.rs:319)
==87==    by 0xD9CD14: kube_client::client::tls::openssl_tls::ssl_connector_builder (tls.rs:269)
==87==    by 0xC3C769: <kube_client::config::Config as kube_client::client::config_ext::ConfigExt>::openssl_ssl_connector_builder (config_ext.rs:254)
==87==    by 0xC3C89E: <kube_client::config::Config as kube_client::client::config_ext::ConfigExt>::openssl_https_connector_with_connector (config_ext.rs:271)
==87==    by 0xC0AB1A: <kube_client::client::builder::ClientBuilder<tower::util::boxed::sync::BoxService<http::request::Request<hyper::body::body::Body>,http::response::Response<alloc::boxed::Box<dyn http_body::Body+Data = bytes::bytes::Bytes+Error = alloc::boxed::Box<dyn std::error::Error+core::marker::Send+core::marker::Sync>+core::marker::Send+core::marker::Unpin>>,alloc::boxed::Box<dyn std::error::Error+core::marker::Send+core::marker::Sync>>> as core::convert::TryFrom<kube_client::config::Config>>::try_from (builder.rs:88)
==87==    by 0xD2EFE7: <kube_client::client::Client as core::convert::TryFrom<kube_client::config::Config>>::try_from (mod.rs:456)
==87==    by 0x34EDE9: kube_client::client::Client::try_default::{{closure}} (mod.rs:128)
==87==    by 0x2CE156: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (mod.rs:91)
==87==    by 0x2BE965: kubectl_delta::main::{{closure}} (main.rs:100)
==87==    by 0x2CD5F8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (mod.rs:91)
==87==    by 0x31E2DF: tokio::park::thread::CachedParkThread::block_on::{{closure}} (thread.rs:267)
==87==
==87== HEAP SUMMARY:
==87==     in use at exit: 0 bytes in 0 blocks
==87==   total heap usage: 0 allocs, 0 frees, 0 bytes allocated
==87==
==87== All heap blocks were freed -- no leaks are possible
==87==
==87== ERROR SUMMARY: 2 errors from 1 contexts (suppressed: 0 from 0)
==87==
==87== 2 errors in context 1 of 1:
==87== Jump to the invalid address stated on the next line
==87==    at 0x0: ???
==87==    by 0xE32AC9: openssl::ssl::SslMethod::tls (mod.rs:319)
==87==    by 0xD9CD14: kube_client::client::tls::openssl_tls::ssl_connector_builder (tls.rs:269)
==87==    by 0xC3C769: <kube_client::config::Config as kube_client::client::config_ext::ConfigExt>::openssl_ssl_connector_builder (config_ext.rs:254)
==87==    by 0xC3C89E: <kube_client::config::Config as kube_client::client::config_ext::ConfigExt>::openssl_https_connector_with_connector (config_ext.rs:271)
==87==    by 0xC0AB1A: <kube_client::client::builder::ClientBuilder<tower::util::boxed::sync::BoxService<http::request::Request<hyper::body::body::Body>,http::response::Response<alloc::boxed::Box<dyn http_body::Body+Data = bytes::bytes::Bytes+Error = alloc::boxed::Box<dyn std::error::Error+core::marker::Send+core::marker::Sync>+core::marker::Send+core::marker::Unpin>>,alloc::boxed::Box<dyn std::error::Error+core::marker::Send+core::marker::Sync>>> as core::convert::TryFrom<kube_client::config::Config>>::try_from (builder.rs:88)
==87==    by 0xD2EFE7: <kube_client::client::Client as core::convert::TryFrom<kube_client::config::Config>>::try_from (mod.rs:456)
==87==    by 0x34EDE9: kube_client::client::Client::try_default::{{closure}} (mod.rs:128)
==87==    by 0x2CE156: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (mod.rs:91)
==87==    by 0x2BE965: kubectl_delta::main::{{closure}} (main.rs:100)
==87==    by 0x2CD5F8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (mod.rs:91)
==87==    by 0x31E2DF: tokio::park::thread::CachedParkThread::block_on::{{closure}} (thread.rs:267)
==87==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==87==
==87== ERROR SUMMARY: 2 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault